docs: add postgres doc.
zeabur/docs pull request #38
Opened 2023-02-19 16:12 UTC by Chia1104

我先新增了 `postgresql.zh-TW` 的文件，你們覺得這裡的說明還有沒有需要多說明或修改的

我再把後續 en 跟 cn 的補上

[preview](https://zeabur-docs-preview.zeabur.app/zh-TW/databases/postgresql)

2023-02-19 16:48 UTC, yuaanlin reviewed
有些工具可能是閱讀文件的讀者第一次看到，所以如果可以在提及這些工具的時候附上一些簡短的介紹和這個工具的相關連結會更好～

2023-02-19 16:48 UTC, yuaanlin commented on pages/databases/postgresql.zh-TW.mdx
> +Zeabur 也可以讓你自行新增資料庫，你可以透過 [PgAdmin](https://www.pgadmin.org/download/) 或 [PostgreSQL CLI](https://www.postgresql.org/download/) 來新增資料庫。
這樣的說法好像怪怪的，應該「本來就要」使用者部署完以後自己建立新的資料庫才對，不是「也可以」自行新增 😂

2023-02-19 16:48 UTC, yuaanlin commented on pages/databases/postgresql.zh-TW.mdx
> + - `template1`
這個好像不用特別提及？這些是 pg 自己建的一些自己需要的資料庫吧（不是給使用者用的）

2023-02-19 16:48 UTC, yuaanlin commented on pages/databases/postgresql.zh-TW.mdx
> +首先你需要先 **Add New Server**，並填入相關資訊。
```suggestion
### PgAdmin

[pgAdmin](https://www.pgadmin.org/) 是 PostgreSQL 最流行、功能最豐富的開源管理和開發平台。 你可以使用 [pgAdmin](https://www.pgadmin.org/) 來連線到你部署在 Zeabur 的 PostgreSQL 資料庫。

首先，你需要先點擊 **Add New Server**，並填入相關資訊：
```

2023-02-19 16:48 UTC, yuaanlin commented on pages/databases/postgresql.zh-TW.mdx
> +```bash copy
```suggestion
### PSQL (sql shell)

[psql](https://www.postgresql.org/docs/current/app-psql.html) 是一個基於終端的 PostgreSQL 工具。它使你能夠以互動方式輸入查詢，將它們發送到 PostgreSQL，並查看查詢結果。此外，[psql](https://www.postgresql.org/docs/current/app-psql.html) 提供了許多各種類似 shell 的功能，以方便編寫腳本和自動執行各種任務。

你可以使用 [psql](https://www.postgresql.org/docs/current/app-psql.html) 來連線到你部署在 Zeabur 的 PostgreSQL 資料庫，只要輸入以下指令：

```bash copy
```

2023-02-20 09:22 UTC, Chia1104 commented
我稍微調整說明了~~

2023-02-20 10:00 UTC, yuaanlin commented
麻煩 @MichaelYuhe 幫忙 review 一下 zh-CN

2023-02-20 10:38 UTC, MichaelYuhe requested changes

2023-02-20 10:38 UTC, MichaelYuhe commented on pages/databases/postgresql.zh-CN.mdx
> +Zeabur 默认的数据库和用户都为 `root`，这里我们需要先自行新增第一个数据库，可以透过以下的方式来新增。
简体中文一般讲 “通过”以下方式

2023-02-20 10:40 UTC, Chia1104 commented on pages/databases/postgresql.zh-CN.mdx
> +Zeabur 默认的数据库和用户都为 `root`，这里我们需要先自行新增第一个数据库，可以透过以下的方式来新增。
了解🙇‍♀️

2023-02-20 10:42 UTC, merged